### ISSUE TITLE
please support more expr (order by, having)

### ISSUE THREAD

**Issue by rfyiamcool** [marianogappa/sqlparser#10]
### question ?

- don't support `order by` in select expr ?
- must not be `a > 100`,  must be `a > '100'` ?

#### sql:

```
query, err := parser.Parse("SELECT a,b,c FROM pusher where a = 'abc' and b = 'hello' ORDER BY a")
if err != nil {
	log.Fatal(err)
}

fmt.Printf("%+#v", query)
```

#### result

```
SELECT a,b,c FROM pusher where a = 'abc' and b = 'hello' ORDER BY a
                                                         ^
expected AND
2021/12/29 23:11:56 expected AND
```

**Comment by marianogappa** [comment]
Hey! Thanks for raising these issues. This isn't actually meant to be a complete SQL parser. It's part of a blog meant to teach people about LL1 parsers.

Here's the blog:
https://marianogappa.github.io/software/2019/06/05/lets-build-a-sql-parser-in-go/

However, every once in a while someone actually uses it for something, so I'm still happy to merge PRs, unless they complicate the code too much.

For now, I'll close this. Thanks anyway, though!
