### ISSUE TITLE
如果查询里面的字段包含了函数的话。。。。

### ISSUE THREAD

**Issue by Zeng-Qe** [marianogappa/sqlparser#11]
比如：select distinct vopenid,substring(tdbank_imp_date_mov,0,8) online_dt,days from test;
这样，到
![image](https://user-images.githubusercontent.com/80379159/159427626-d7532516-b702-45e8-8652-2d56ce23d812.png)
代码这一段的话就无法进行下去了

**Comment by marianogappa** [comment]
Hey! Thanks for raising this issue. You're right, the parser does not support functions anywhere. This isn't actually meant to be a complete SQL parser. It's part of a blog meant to teach people about LL1 parsers.

Here's the blog:
https://marianogappa.github.io/software/2019/06/05/lets-build-a-sql-parser-in-go/

However, every once in a while someone actually uses it for something, so I'm still happy to merge PRs, unless they complicate the code too much.

For now, I'll close this. Thanks anyway, though!
