### ISSUE TITLE
minio also has exactly the same thing

### ISSUE THREAD

**Issue by ghost** [marianogappa/sqlparser#2]
query CSV using SQL.

https://github.com/minio/minio/blob/master/pkg/s3select/sql/parser.go

Yours handles updates though and DDL ?

**Comment by marianogappa** [comment]
I'm afraid this package doesn't query CSVs at all. It only parses SQL queries. It does parse `UPDATE`/`DELETE` queries, yes.
That link doesn't seem to be an LL(1) parser, and seems to handle reasonably complex `SELECT` queries including functions. It only seems to parse `SELECT` queries, though.
