### ISSUE TITLE
Feature Request: Field aliases

### ISSUE THREAD

**Issue by coreybutler** [marianogappa/sqlparser#5]
I have a use case where field names in the result need to be accessible by a different name. This is typically done with field name aliases in the SQL statement. For example:

```sql
SELECT a as altNameA, b as altNameB, c
FROM 'file.csv'
```

**Comment by marianogappa** [comment]
Hey @coreybutler, sorry it took me so long to see this, my notifications were messed up! Thank you for contributing 👍
