### ISSUE TITLE
If the table symbol is ``, cannot be read

### ISSUE THREAD

**Issue by Rbingo** [marianogappa/sqlparser#9]
example:
 SELECT * FROM `table` WHERE  `id` = 123

**Comment by Rbingo** [comment]
Lack of `limit`

**Comment by marianogappa** [comment]
Hey! Thanks for raising these issues. This isn't actually meant to be a complete SQL parser. It's part of a blog meant to teach people about LL1 parsers.

Here's the blog:
https://marianogappa.github.io/software/2019/06/05/lets-build-a-sql-parser-in-go/

However, every once in a while someone actually uses it for something, so I'm still happy to merge PRs, unless they complicate the code too much.

For now, I'll close this. Thanks anyway, though!
